### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by lwilhoit** [gruns/icecream#117]
I just started getting an IndentationError for any calls to ic. I actually made no changes to my script but the next time I ran it I now get that error. My python script is quite large and unfortunately I cannot replicate the error with a smaller script. Here is the full traceback:

Traceback (most recent call last):
  File "C:\docs\python\gui\pur.py", line 985, in <lambda>
    self.ui.which_rate_ai_lw.itemClicked.connect(lambda: self.setSelectList('ai_name', 'rate'))
  File "C:\docs\python\gui\pur.py", line 1454, in setSelectList
    ic(self.ai_list)
  File "C:\docs\python\gui\pur_env\lib\site-packages\icecream\icecream.py", line 181, in __call__
    out = self._format(callFrame, *args)
  File "C:\docs\python\gui\pur_env\lib\site-packages\icecream\icecream.py", line 215, in _format
    out = self._formatArgs(
  File "C:\docs\python\gui\pur_env\lib\site-packages\icecream\icecream.py", line 222, in _formatArgs
    sanitizedArgStrs = [
  File "C:\docs\python\gui\pur_env\lib\site-packages\icecream\icecream.py", line 223, in <listcomp>
    source.get_text_with_indentation(arg)
  File "C:\docs\python\gui\pur_env\lib\site-packages\icecream\icecream.py", line 119, in get_text_with_indentation
    result = self.asttokens().get_text(node)
  File "C:\docs\python\gui\pur_env\lib\site-packages\executing\executing.py", line 416, in asttokens
    return ASTTokens(
  File "C:\docs\python\gui\pur_env\lib\site-packages\asttokens\asttokens.py", line 59, in __init__
    self._tokens = list(self._generate_tokens(source_text))
  File "C:\docs\python\gui\pur_env\lib\site-packages\asttokens\asttokens.py", line 85, in _generate_tokens
    for index, tok in enumerate(tokenize.generate_tokens(io.StringIO(text).readline)):
  File "C:\Users\lwilhoit\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 514, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 1680
    def setAdjuvants(self):
IndentationError: unindent does not match any outer indentation level

**Comment by alexmojaki** [comment]
Interesting. Please see if you get the same error with this script:

```python
import executing

executing.Source.for_filename("pur.py").asttokens()
```

If so, you should be able to delete parts of `pur.py` to narrow down the problem.

**Comment by lwilhoit** [comment]
I finally got a shorter script that resulted in this error, which occurs when there is a "\" at the beginning of a line:

from icecream import ic

def ic_test_func():
    test_value = 3

    ic(test_value)
\
    if test_value == 3:
        ic('value is 3')
    else:
        ic('value is not 3')

ic_test_func()

**Comment by lwilhoit** [comment]
My previous code did not format correctly.  See the attached file
[ic_test_func.txt](https://github.com/gruns/icecream/files/8146997/ic_test_func.txt)
.

**Comment by lwilhoit** [comment]
No, that was just an overlooked and accidental hitting the “\” key.

**Comment by salabim** [comment]
I also find it weird that the program runs at all.
So I made a small test script

def m():
    print(1)
\
    if True:
        print(2)
    else:
        print(3)
        
m()

, just to test this behaviour. Under Python 3.8 and below this indeed gives an IndentationError at compile time.
But, under Python 3.10 this just runs! No idea why.

**Comment by salabim** [comment]
I also found it weird.
In order to see check the behaviour, I made a small test script
```
def m():
    print(1)
\
    if True:
        print(2)
    else:
        print(3)
        
m()
```'
Under Python 3.6 and 3.8 this indeed gives an IndentationError at comple time.
But, under Python 3.10 it runs and results in:
```
1
2
```
No idea what's behind that.

**Comment by alexmojaki** [comment]
It first works in 3.9. Looks like a quirk of the new 3.10 PEG parser.

I don't think icecream should deal with this. Maybe open a bug on bugs.python.org if there isn't one already.

**Comment by gruns** [comment]
@alexmojaki agreed this is beyond the scope of icecream 👍 

@lwilhoit really interesting find. ive never seen py code formatted like this, either. thanks for opening this issue!
