### ISSUE TITLE
Add option to skip show of source code

### ISSUE THREAD

**Issue by Joss** [gruns/icecream#22]
The problem is when I build the project with [PyInstaller](https://www.pyinstaller.org) in onefile mode the iceream can't find the source code. I understand that I can to use ic.disable() but I want to send the exe file with console enabled for testing purposes.

Could you add an option to disable show of sources or simply don't break the app when they are absent? Thanks.

`Traceback (most recent call last):
  File "app.py", line 79, in <module>
  File "app.py", line 23, in process
  File "site-packages\icecream\icecream.py", line 322, in __call__
  File "site-packages\icecream\icecream.py", line 346, in _format
  File "site-packages\icecream\icecream.py", line 435, in _formatContext
  File "site-packages\icecream\icecream.py", line 453, in _getContext
  File "site-packages\icecream\icecream.py", line 147, in getCallSourceLines
  File "inspect.py", line 968, in getsource
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code`

**Comment by gruns** [comment]
Fixed in https://github.com/gruns/icecream/commit/74cc0a0261ede81e54d5241d80f0477b59b58d4c.

This fix will ship in the forthcoming icecream v1.3.1.

**Comment by gruns** [comment]
Fix shipped in v1.3.1, hot off the presses.

Upgrade with

```
$ pip install icecream --upgrade
```

Thank you again, @Joss, for bringing this issue to my attention. Don't hesitate to let me know if there's anything I can do for you.
